
  apiVersion: v1
  kind: Service
  metadata:
    name: dronefleet-flight-access

  spec:
    # This defines which pods are going to be represented by this Service
    # The service becomes a network endpoint for either other services
    # or maybe external users to connect to (eg browser)
    selector:
      app: dronefleet-flight-access

    ports:
      - name: http
        port: 8080
        nodePort: 30050

    type: NodePort

---
 apiVersion: v1
 kind: Service
 metadata:
    name: dronefleet-flight-upload

 spec:
    # This defines which pods are going to be represented by this Service
    # The service becomes a network endpoint for either other services
    # or maybe external users to connect to (eg browser)
    selector:
      app: dronefleet-flight-upload

    ports:
      - name: http
        port: 8080
        nodePort: 30060

    type: NodePort

---
  apiVersion: v1
  kind: Service
  metadata:
    name: drone-api-gateway

  spec:
    # This defines which pods are going to be represented by this Service
    # The service becomes a network endpoint for either other services
    # or maybe external users to connect to (eg browser)
    selector:
      app: drone-api-gateway

    ports:
      - name: http
        port: 8080
        nodePort: 30030

    type: NodePort
