

#Drone-flight-data-access Service
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: dronefleet-flight-access
  spec:
    selector:
      matchLabels:
        app: dronefleet-flight-access
    replicas: 1
    template: # template for the pods
      metadata:
        labels:
          app: dronefleet-flight-access
      spec:
        containers:
        - name: dronefleet-flight-access
          image: venkatgenxdev/drone-flight-data-access:release13
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: local-microservice

---
#Drone-flight-data-Upload Service
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: dronefleet-flight-upload
  spec:
    selector:
      matchLabels:
        app: dronefleet-flight-upload
    replicas: 1
    template: # template for the pods
      metadata:
        labels:
          app: dronefleet-flight-upload
      spec:
        containers:
        - name: dronefleet-flight-upload
          image: venkatgenxdev/drone-flight-data-upload:release6
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: local-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-api-gateway
spec:
  selector:
    matchLabels:
      app: drone-api-gateway
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: drone-api-gateway
    spec:
      containers:
      - name: drone-api-gateway
        image: venkatgenxdev/drone-flight-gateway-api:version1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: local-microservice
