FROM openjdk:8u131-jre

MAINTAINER Venkatesh Gaduputi "venkateshmac@icloud.com"

ADD ./target/drone-flight-data-access-0.0.1-SNAPSHOT.jar webapp.jar

EXPOSE 8080

CMD ["java","-jar","webapp.jar"]
